"""Data models for project analysis results."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class Language(str, Enum):
    PYTHON = "python"
    JAVASCRIPT = "javascript"
    TYPESCRIPT = "typescript"
    GO = "go"
    RUST = "rust"
    JAVA = "java"


class Framework(str, Enum):
    FASTAPI = "fastapi"
    DJANGO = "django"
    FLASK = "flask"
    EXPRESS = "express"
    NEXTJS = "nextjs"
    GIN = "gin"
    SPRING = "spring"
    ACTIX = "actix"


class PackageManager(str, Enum):
    PIP = "pip"
    POETRY = "poetry"
    PIPENV = "pipenv"
    NPM = "npm"
    YARN = "yarn"
    PNPM = "pnpm"
    CARGO = "cargo"
    GO_MOD = "go_mod"
    MAVEN = "maven"
    GRADLE = "gradle"


class TestRunner(str, Enum):
    PYTEST = "pytest"
    UNITTEST = "unittest"
    JEST = "jest"
    MOCHA = "mocha"
    VITEST = "vitest"
    GO_TEST = "go_test"
    CARGO_TEST = "cargo_test"
    JUNIT = "junit"


class Linter(str, Enum):
    FLAKE8 = "flake8"
    PYLINT = "pylint"
    BLACK = "black"
    RUFF = "ruff"
    MYPY = "mypy"
    ESLINT = "eslint"
    PRETTIER = "prettier"
    GOLANGCI_LINT = "golangci_lint"
    CLIPPY = "clippy"
    RUSTFMT = "rustfmt"
    CHECKSTYLE = "checkstyle"


class DatabaseType(str, Enum):
    POSTGRESQL = "postgresql"
    MYSQL = "mysql"
    SQLITE = "sqlite"
    MONGODB = "mongodb"
    REDIS = "redis"


@dataclass
class LanguageInfo:
    """Detected language with version hints and file count."""
    language: Language
    file_count: int = 0
    versions: list[str] = field(default_factory=list)
    is_primary: bool = False


@dataclass
class ProjectAnalysis:
    """Complete analysis result for a project directory."""
    project_name: str
    project_path: str
    languages: list[LanguageInfo] = field(default_factory=list)
    frameworks: list[Framework] = field(default_factory=list)
    package_managers: list[PackageManager] = field(default_factory=list)
    test_runners: list[TestRunner] = field(default_factory=list)
    linters: list[Linter] = field(default_factory=list)
    databases: list[DatabaseType] = field(default_factory=list)
    has_docker: bool = False
    has_ci: bool = False
    entry_points: list[str] = field(default_factory=list)
    port: Optional[int] = None

    @property
    def primary_language(self) -> Optional[Language]:
        """Return the primary (most used) language."""
        for lang in self.languages:
            if lang.is_primary:
                return lang.language
        return self.languages[0].language if self.languages else None

    @property
    def primary_package_manager(self) -> Optional[PackageManager]:
        """Return the first detected package manager."""
        return self.packages_managers[0] if self.package_managers else None

    def to_dict(self) -> dict:
        """Serialize to dictionary."""
        return {
            "project_name": self.project_name,
            "project_path": self.project_path,
            "languages": [
                {"language": li.language.value, "file_count": li.file_count,
                 "versions": li.versions, "is_primary": li.is_primary}
                for li in self.languages
            ],
            "frameworks": [f.value for f in self.frameworks],
            "package_managers": [pm.value for pm in self.package_managers],
            "test_runners": [tr.value for tr in self.test_runners],
            "linters": [l.value for l in self.linters],
            "databases": [d.value for d in self.databases],
            "has_docker": self.has_docker,
            "has_ci": self.has_ci,
            "entry_points": self.entry_points,
            "port": self.port,
        }


@dataclass
class GeneratorConfig:
    """Configuration for pipeline generation."""
    platforms: list[str] = field(default_factory=lambda: ["github_actions"])
    include_docker: bool = True
    include_security: bool = True
    include_deploy: bool = False
    deploy_provider: Optional[str] = None  # vercel, heroku, aws, gcp
    python_versions: list[str] = field(default_factory=lambda: ["3.11", "3.12"])
    node_versions: list[str] = field(default_factory=lambda: ["18", "20", "22"])
    go_versions: list[str] = field(default_factory=lambda: ["1.21", "1.22"])
    rust_toolchains: list[str] = field(default_factory=lambda: ["stable"])
    java_versions: list[str] = field(default_factory=lambda: ["17", "21"])
    output_dir: Optional[str] = None  # None = same as project dir


@dataclass
class GeneratedFile:
    """A file generated by a pipeline generator."""
    path: str
    content: str
    description: str
    overwrite_warning: bool = False
